### ISSUE TITLE
[Feedback] General Concerns About Configuration

### ISSUE THREAD

**Issue by instead1337** [mewostick/Creosynth#12]
Here’s a friendlier version of your message that maintains your points:

---

Hi again,

I hope you're doing well!

I wanted to discuss a couple of things in the [optimise.yml](https://github.com/mewostick/Creosynth/blob/main/playbook/Configuration/Tasks/optimise.yml) file:

First, regarding this snippet:

```yaml
- !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications'
    value: 'GlobalUserDisabled'
    data: '1'
    type: REG_DWORD
```

I’ve noticed that this change breaks notifications for AppX apps from browsers and other programs. I understand the goal is to disable background app activity to free up RAM, but does this compromise stability?

Also, I see you're using `- !cmd:` for the following:

```yaml
# set processor scheduling to user choice
- !cmd
  command: 'reg add "HKLM\SYSTEM\CurrentControlSet\Control\PriorityControl" /v Win32PrioritySeparation /t REG_DWORD /d 24 /f'
  wait: true
  option: background-services

- !cmd
  command: 'reg add "HKLM\SYSTEM\CurrentControlSet\Control\PriorityControl" /v Win32PrioritySeparation /t REG_DWORD /d 38 /f'
  wait: true
  option: optimise-for-programs
```

Why use `- !cmd:` here when you could use `- !registryValue:` instead?

Lastly, in the same file, you're clearing the cache for the following:

```yaml
- !appx: {name: '*Client.CBS*', operation: clearCache}
- !appx: {name: '*StartMenuExperienceHost*', operation: clearCache}
- !appx: {name: '*Windows.Search*', operation: clearCache}
```

But it seems like you're cleaning these twice, as the same code appears in [start-clean.yml](https://github.com/mewostick/Creosynth/blob/main/playbook/Configuration/Tasks/start-clean.yml). 

I just wanted to point out these little inconsistencies. I truly hope your playbook will improve in the future - I'm optimistic about it
